server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/admin/**, /api/test/**
          filters:
            - StripPrefix=0

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

# AJOUTEZ CES LIGNES POUR ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose tous les endpoints Actuator
  endpoint:
    gateway:
      enabled: true  # Active spécifiquement l'endpoint gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/